source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MPParallaxView_Example', :exclusive => true do
  pod "MPParallaxView", :path => "../"
end

target 'MPParallaxView_Tests', :exclusive => true do
  pod "MPParallaxView", :path => "../"

  
end
